apiVersion: apps/v1
kind: Deployment
metadata:
name: forklift-validation
labels:
  app: forklift-validation
spec:
replicas: 1
selector:
  matchLabels:
    app: forklift-validation
template:
  metadata:
    labels:
      app: forklift-validation
    name: forklift-validation
  spec:
    containers:
      - name: forklift-validation
        image: 'quay.io/konveyor/forklift-validation:latest'
        ports:
          - name: http
            containerPort: 8181
        env:
          - name: CA_TLS_CERTIFICATE
            value: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: INVENTORY_SERVICE
            value: forklift-inventory
          - name: TLS_ENABLED
            value: 'true'
          - name: TLS_CERT_FILE
            value: /var/run/secrets/forklift-validation-serving-cert/tls.crt
          - name: TLS_KEY_FILE
            value: /var/run/secrets/forklift-validation-serving-cert/tls.key
        volumeMounts:
          - name: forklift-inventory-serving-cert
            mountPath: /var/run/secrets/forklift-validation-serving-cert
    volumes:
      - name: forklift-validation-serving-cert
        secret:
          secretName: forklift-validation-serving-cert
          defaultMode: 420