kind: Service
apiVersion: v1
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: forklift-validation-serving-cert
  name: forklift-validation
  labels:
    app: forklift-validation
spec:
  type: ClusterIP
  selector:
    app: forklift-validation
  ports:
    - name: http
      protocol: TCP
      port: 8181
      targetPort: 8181